##Business Understanding

# **Business Objective**

Tujuan utama proyek analisis ini adalah untuk mengetahui kehidupan sosial dan ekonomi masyarakat Indonesia pada tahun 2021. Hal ini meliputi wilayah apa yang memiliki persentase kemiskinan paling tinggi atau sebaliknya, angka harapan hidup dari setiap wilayah, dan hal-hal lainnya yang berhubungan dengan kehidupan sosial dan ekonomi masyrakat Indonesia. Selain itu, juga untuk mengetahui seberapa besar dampak pendidikan untuk perekenomian di Indonesia.

# **Assess Situation**

Situasi yang mendasari analisis ini untuk melihat apakah arah ekonomi dan sosial di Indonesia sudah benar atau tidak. Masih terdapat beberapa ketimpangan ekonomi yang terjadi di masa sekarang. Wilayah yang seharusnya mendapat perhatian lebih justru diabaikan.

# **Data Understanding**

Sumber data: https://www.kaggle.com/datasets/dannytheodore/socio-economic-of-indonesia-in-2021

In [57]:
import pandas as pd

df = pd.read_csv("/content/Data AVD Praktikum.csv")

df

,province,cities_reg,poorpeople_percentage,reg_gdp,life_exp,avg_schooltime,exp_percap
0,Aceh,Simeulue,18.98,2.275,65.240,9.48,7148
1,Aceh,Aceh Singkil,20.36,2.425,67.355,8.68,8776
2,Aceh,Aceh Selatan,13.18,5.531,64.360,8.88,8180
3,Aceh,Aceh Tenggara,13.41,5.063,68.155,9.67,8030
4,Aceh,Aceh Timur,14.45,10.616,68.705,8.21,8577
...,...,...,...,...,...,...,...
509,Papua,Puncak,36.26,1.438,66.060,2.16,5412
510,Papua,Dogiyai,28.81,1.356,65.845,4.94,5415
511,Papua,Intan Jaya,41.66,1.274,65.580,3.09,5328
512,Papua,Deiyai,40.59,1.439,65.355,3.25,4673
513,Papua,Kota Jayapura,11.39,32.207,70.455,11.57,14937

**Pemeriksaan Tipe Data**

In [58]:
df.dtypes

province                  object
cities_reg                object
poorpeople_percentage    float64
reg_gdp                  float64
life_exp                 float64
avg_schooltime           float64
exp_percap                 int64
dtype: object

**Menampilkan berapa kolom dan baris**

In [59]:
df.shape

(514, 7)

**Statistik Deskriptif dari data (Mean,Median,Min,Max,Quartil)**

In [60]:
df.describe()

,poorpeople_percentage,reg_gdp,life_exp,avg_schooltime,exp_percap
count,514.000000,514.000000,514.000000,514.000000,514.000000
mean,12.273152,34.798333,69.619076,8.436615,10324.787938
std,7.458703,84.155498,3.455911,1.630842,2717.144186
min,2.380000,1.042000,55.370000,1.420000,3976.000000
25%,7.150000,5.587500,67.336250,7.510000,8574.000000
50%,10.455000,13.068500,69.922500,8.305000,10196.500000
75%,14.887500,28.849500,72.018750,9.337500,11719.000000
max,41.660000,819.000000,77.855000,12.830000,23888.000000

Dapat dilihat di bawah karena ini merupakan data mengenai wilayah-wilayah di Indonesia, jadi masing-masing memiliki value yang unik.

In [61]:
df.value_counts()

province          cities_reg         poorpeople_percentage  reg_gdp  life_exp  avg_schooltime  exp_percap
Aceh              Aceh Barat         18.81                  8.116    67.945    9.55            9593          1
Sulawesi Selatan  Kota Palopo        8.14                   8.025    70.865    10.94           13117         1
Papua Barat       Pegunungan Arfak   34.70                  218.000  67.260    5.12            5009          1
                  Maybrat            31.39                  732.000  65.240    6.96            5245          1
                  Manokwari Selatan  29.30                  819.000  67.600    6.63            5505          1
                                                                                                            ..
Jawa Timur        Pacitan            15.11                  15.785   72.030    7.61            8887          1
                  Ngawi              15.57                  20.271   72.355    7.26            11459         1
                  Nganjuk            11.85                  26.601   71.550    7.78            12172         1
                  Mojokerto          10.62                  81.941   72.535    8.64            12844         1
Sumatera Utara    Toba Samosir       8.99                   7.845    70.210    10.57           12224         1
Name: count, Length: 514, dtype: int64

**Mencari korelasi**

In [62]:
df.corr(numeric_only=True)

,poorpeople_percentage,reg_gdp,life_exp,avg_schooltime,exp_percap
poorpeople_percentage,1.000000,-0.078131,-0.538820,-0.543909,-0.644222
reg_gdp,-0.078131,1.000000,0.209147,0.165403,0.333952
life_exp,-0.538820,0.209147,1.000000,0.414511,0.565775
avg_schooltime,-0.543909,0.165403,0.414511,1.000000,0.668847
exp_percap,-0.644222,0.333952,0.565775,0.668847,1.000000

Untuk korelasi positif yaitu terdapat di kolom rata-rata lama pendidikan dengan pengeluaran per kapita, hal ini bisa disimpulkan bahwa semakin lama penduduk melakukan pendidikan semakin tinggi juga pengeluaran per kapita-nya.

Sedangkan, untuk korelasi negatif terdapat di kolom persentase penduduk miskin dengan rata-rata lama pendidikan, dapat disimpulkan bahwa semakin lama penduduk melakukan pendidikan semakin rendah pula persentase penduduk miskinnya.

# **Data Preparation**

Sumber data: https://www.kaggle.com/datasets/dannytheodore/socio-economic-of-indonesia-in-2021

**Pengecheckan untuk data apakah ada missing values**

In [63]:
print((df.isna().sum() / len(df)) * 100)

province                 0.0
cities_reg               0.0
poorpeople_percentage    0.0
reg_gdp                  0.0
life_exp                 0.0
avg_schooltime           0.0
exp_percap               0.0
dtype: float64

Karna tidak ada missing values, jadi tidak ada yang perlu ditambahin dari datanya

**Mengecheck data duplikat**

In [64]:
df.duplicated().sum()

0

Hasilnya tidak ada data yang duplikat

**Outlier**

Jika ada outlier di dalam data saya itu tidak dihapus, karena nilai tersebut mewaikili fenomena nyata yaitu nilai yang telah dikumpulkan berdasarkan fakta.

**Inconsistent Values**

In [65]:
# prompt: Check inconsistent values

# Check for inconsistent values in categorical columns
for col in df.select_dtypes(include=['object']).columns:
  print(f"Unique values in column '{col}':")
  print(df[col].unique())
  print("-" * 20)

Unique values in column 'province':
['Aceh' 'Sumatera Utara' 'Sumatera Barat' 'Riau' 'Jambi'
 'Sumatera Selatan' 'Bengkulu' 'Lampung' 'Kepulauan Bangka Belitung'
 'Kepulauan Riau' 'DKI Jakarta' 'Jawa Barat' 'Jawa Tengah' 'DI Yogyakarta'
 'Jawa Timur' 'Banten' 'Bali' 'Nusa Tenggara Barat' 'Nusa Tenggara Timur'
 'Kalimantan Barat' 'Kalimantan Tengah' 'Kalimantan Selatan'
 'Kalimantan Timur' 'Kalimantan Utara' 'Sulawesi Utara' 'Sulawesi Tengah'
 'Sulawesi Selatan' 'Sulawesi Tenggara' 'Gorontalo' 'Sulawesi Barat'
 'Maluku' 'Maluku Utara' 'Papua Barat' 'Papua']
--------------------
Unique values in column 'cities_reg':
['Simeulue' 'Aceh Singkil' 'Aceh Selatan' 'Aceh Tenggara' 'Aceh Timur'
 'Aceh Tengah' 'Aceh Barat' 'Aceh Besar' 'Pidie' 'Bireuen' 'Aceh Utara'
 'Aceh Barat Daya' 'Gayo Lues' 'Aceh Tamiang' 'Nagan Raya' 'Aceh Jaya'
 'Bener Meriah' 'Pidie Jaya' 'Kota Banda Aceh' 'Kota Sabang' 'Kota Langsa'
 'Kota Lhokseumawe' 'Kota Subulussalam' 'Nias' 'Mandailing Natal'
 'Tapanuli Selatan' 'Tapanuli Tengah' 'Tapanuli Utara' 'Toba Samosir'
 'Labuhan Batu' 'Asahan' 'Simalungun' 'Dairi' 'Karo' 'Deli Serdang'
 'Langkat' 'Nias Selatan' 'Humbang Hasundutan' 'Pakpak Bharat' 'Samosir'
 'Serdang Bedagai' 'Batu Bara' 'Padang Lawas Utara' 'Padang Lawas'
 'Labuhan Batu Selatan' 'Labuhan Batu Utara' 'Nias Utara' 'Nias Barat'
 'Kota Sibolga' 'Kota Tanjung Balai' 'Kota Pematang Siantar'
 'Kota Tebing Tinggi' 'Kota Medan' 'Kota Binjai' 'Kota Padangsidimpuan'
 'Kota Gunungsitoli' 'Kepulauan Mentawai' 'Pesisir Selatan' 'Solok'
 'Sijunjung' 'Tanah Datar' 'Padang Pariaman' 'Agam' 'Lima Puluh Kota'
 'Pasaman' 'Solok Selatan' 'Dharmasraya' 'Pasaman Barat' 'Kota Padang'
 'Kota Solok' 'Kota Sawah Lunto' 'Kota Padang Panjang' 'Kota Bukittinggi'
 'Kota Payakumbuh' 'Kota Pariaman' 'Kuantan Singingi' 'Indragiri Hulu'
 'Indragiri Hilir' 'Pelalawan' 'Siak' 'Kampar' 'Rokan Hulu' 'Bengkalis'
 'Rokan Hilir' 'Kepulauan Meranti' 'Kota Pekanbaru' 'Kota Dumai' 'Kerinci'
 'Merangin' 'Sarolangun' 'Batang Hari' 'Muaro Jambi'
 'Tanjung Jabung Timur' 'Tanjung Jabung Barat' 'Tebo' 'Bungo' 'Kota Jambi'
 'Kota Sungai Penuh' 'Ogan Komering Ulu' 'Ogan Komering Ilir' 'Muara Enim'
 'Lahat' 'Musi Rawas' 'Musi Banyuasin' 'Banyu Asin'
 'Ogan Komering Ulu Selatan' 'Ogan Komering Ulu Timur' 'Ogan Ilir'
 'Empat Lawang' 'Penukal Abab Lematang Ilir' 'Musi Rawas Utara'
 'Kota Palembang' 'Kota Prabumulih' 'Kota Pagar Alam' 'Kota Lubuklinggau'
 'Bengkulu Selatan' 'Rejang Lebong' 'Bengkulu Utara' 'Kaur' 'Seluma'
 'Mukomuko' 'Lebong' 'Kepahiang' 'Bengkulu Tengah' 'Kota Bengkulu'
 'Lampung Barat' 'Tanggamus' 'Lampung Selatan' 'Lampung Timur'
 'Lampung Tengah' 'Lampung Utara' 'Way Kanan' 'Tulangbawang' 'Pesawaran'
 'Pringsewu' 'Mesuji' 'Tulang Bawang Barat' 'Pesisir Barat'
 'Kota Bandar Lampung' 'Kota Metro' 'Bangka' 'Belitung' 'Bangka Barat'
 'Bangka Tengah' 'Bangka Selatan' 'Belitung Timur' 'Kota Pangkal Pinang'
 'Karimun' 'Bintan' 'Natuna' 'Lingga' 'Kepulauan Anambas' 'Kota Batam'
 'Kota Tanjung Pinang' 'Kepulauan Seribu' 'Kota Jakarta Selatan'
 'Kota Jakarta Timur' 'Kota Jakarta Pusat' 'Kota Jakarta Barat'
 'Kota Jakarta Utara' 'Bogor' 'Sukabumi' 'Cianjur' 'Bandung' 'Garut'
 'Tasikmalaya' 'Ciamis' 'Kuningan' 'Cirebon' 'Majalengka' 'Sumedang'
 'Indramayu' 'Subang' 'Purwakarta' 'Karawang' 'Bekasi' 'Bandung Barat'
 'Pangandaran' 'Kota Bogor' 'Kota Sukabumi' 'Kota Bandung' 'Kota Cirebon'
 'Kota Bekasi' 'Kota Depok' 'Kota Cimahi' 'Kota Tasikmalaya' 'Kota Banjar'
 'Cilacap' 'Banyumas' 'Purbalingga' 'Banjarnegara' 'Kebumen' 'Purworejo'
 'Wonosobo' 'Magelang' 'Boyolali' 'Klaten' 'Sukoharjo' 'Wonogiri'
 'Karanganyar' 'Sragen' 'Grobogan' 'Blora' 'Rembang' 'Pati' 'Kudus'
 'Jepara' 'Demak' 'Semarang' 'Temanggung' 'Kendal' 'Batang' 'Pekalongan'
 'Pemalang' 'Tegal' 'Brebes' 'Kota Magelang' 'Kota Surakarta'
 'Kota Salatiga' 'Kota Semarang' 'Kota Pekalongan' 'Kota Tegal'
 'Kulon Progo' 'Bantul' 'Gunung Kidul' 'Sleman' 'Kota Yogyakarta'
 'Pacitan' 'Ponorogo' 'Trenggalek' 'Tulungagung' 'Blitar' 'Kediri'
 'Malang' 'Lumajang' 'Jember' 'Banyuwangi' 'Bondowoso' 'Situbondo'
 'Probolinggo' 'Pasuruan' 'Sidoarjo' 'Mojokerto' 'Jombang' 'Nganjuk'
 'Madiun' 'Magetan' 'Ngawi' 'Bojonegoro' 'Tuban' 'Lamongan' 'Gresik'
 'Bangkalan' 'Sampang' 'Pamekasan' 'Sumenep' 'Kota Kediri' 'Kota Blitar'
 'Kota Malang' 'Kota Probolinggo' 'Kota Pasuruan' 'Kota Mojokerto'
 'Kota Madiun' 'Kota Surabaya' 'Kota Batu' 'Pandeglang' 'Lebak'
 'Tangerang' 'Serang' 'Kota Tangerang' 'Kota Cilegon' 'Kota Serang'
 'Kota Tangerang Selatan' 'Jembrana' 'Tabanan' 'Badung' 'Gianyar'
 'Klungkung' 'Bangli' 'Karang Asem' 'Buleleng' 'Kota Denpasar'
 'Lombok Barat' 'Lombok Tengah' 'Lombok Timur' 'Sumbawa' 'Dompu' 'Bima'
 'Sumbawa Barat' 'Lombok Utara' 'Kota Mataram' 'Kota Bima' 'Sumba Barat'
 'Sumba Timur' 'Kupang' 'Timor Tengah Selatan' 'Timor Tengah Utara' 'Belu'
 'Alor' 'Lembata' 'Flores Timur' 'Sikka' 'Ende' 'Ngada' 'Manggarai'
 'Rote Ndao' 'Manggarai Barat' 'Sumba Tengah' 'Sumba Barat Daya' 'Nagekeo'
 'Manggarai Timur' 'Sabu Raijua' 'Malaka' 'Kota Kupang' 'Sambas'
 'Bengkayang' 'Landak' 'Pontianak' 'Sanggau' 'Ketapang' 'Sintang'
 'Kapuas Hulu' 'Sekadau' 'Melawi' 'Kayong Utara' 'Kubu Raya'
 'Kota Pontianak' 'Kota Singkawang' 'Kotawaringin Barat'
 'Kotawaringin Timur' 'Kapuas' 'Barito Selatan' 'Barito Utara' 'Sukamara'
 'Lamandau' 'Seruyan' 'Katingan' 'Pulang Pisau' 'Gunung Mas'
 'Barito Timur' 'Murung Raya' 'Kota Palangka Raya' 'Tanah Laut'
 'Kota Baru' 'Banjar' 'Barito Kuala' 'Tapin' 'Hulu Sungai Selatan'
 'Hulu Sungai Tengah' 'Hulu Sungai Utara' 'Tabalong' 'Tanah Bumbu'
 'Balangan' 'Kota Banjarmasin' 'Kota Banjar Baru' 'Paser' 'Kutai Barat'
 'Kutai Kartanegara' 'Kutai Timur' 'Berau' 'Penajam Paser Utara'
 'Mahakam Hulu' 'Kota Balikpapan' 'Kota Samarinda' 'Kota Bontang'
 'Malinau' 'Bulungan' 'Tana Tidung' 'Nunukan' 'Kota Tarakan'
 'Bolaang Mongondow' 'Minahasa' 'Kepulauan Sangihe' 'Kepulauan Talaud'
 'Minahasa Selatan' 'Minahasa Utara' 'Bolaang Mongondow Utara'
 'Siau Tagulandang Biaro' 'Minahasa Tenggara' 'Bolaang Mongondow Selatan'
 'Bolaang Mongondow Timur' 'Kota Manado' 'Kota Bitung' 'Kota Tomohon'
 'Kota Kotamobagu' 'Banggai Kepulauan' 'Banggai' 'Morowali' 'Poso'
 'Donggala' 'Toli-Toli' 'Buol' 'Parigi Moutong' 'Tojo Una-Una' 'Sigi'
 'Banggai Laut' 'Morowali Utara' 'Kota Palu' 'Kepulauan Selayar'
 'Bulukumba' 'Bantaeng' 'Jeneponto' 'Takalar' 'Gowa' 'Sinjai' 'Maros'
 'Pangkajene Dan Kepulauan' 'Barru' 'Bone' 'Soppeng' 'Wajo'
 'Sidenreng Rappang' 'Pinrang' 'Enrekang' 'Luwu' 'Tana Toraja'
 'Luwu Utara' 'Luwu Timur' 'Toraja Utara' 'Kota Makassar' 'Kota Parepare'
 'Kota Palopo' 'Buton' 'Muna' 'Konawe' 'Kolaka' 'Konawe Selatan' 'Bombana'
 'Wakatobi' 'Kolaka Utara' 'Buton Utara' 'Konawe Utara' 'Kolaka Timur'
 'Konawe Kepulauan' 'Muna Barat' 'Buton Tengah' 'Buton Selatan'
 'Kota Kendari' 'Kota Baubau' 'Boalemo' 'Gorontalo' 'Pohuwato'
 'Bone Bolango' 'Gorontalo Utara' 'Kota Gorontalo' 'Majene'
 'Polewali Mandar' 'Mamasa' 'Mamuju' 'Mamuju Utara' 'Mamuju Tengah'
 'Maluku Tenggara Barat' 'Maluku Tenggara' 'Maluku Tengah' 'Buru'
 'Kepulauan Aru' 'Seram Bagian Barat' 'Seram Bagian Timur'
 'Maluku Barat Daya' 'Buru Selatan' 'Kota Ambon' 'Kota Tual'
 'Halmahera Barat' 'Halmahera Tengah' 'Kepulauan Sula' 'Halmahera Selatan'
 'Halmahera Utara' 'Halmahera Timur' 'Pulau Morotai' 'Pulau Taliabu'
 'Kota Ternate' 'Kota Tidore Kepulauan' 'Fakfak' 'Kaimana' 'Teluk Wondama'
 'Teluk Bintuni' 'Manokwari' 'Sorong Selatan' 'Sorong' 'Raja Ampat'
 'Tambrauw' 'Maybrat' 'Manokwari Selatan' 'Pegunungan Arfak' 'Kota Sorong'
 'Merauke' 'Jayawijaya' 'Jayapura' 'Nabire' 'Kepulauan Yapen'
 'Biak Numfor' 'Paniai' 'Puncak Jaya' 'Mimika' 'Boven Digoel' 'Mappi'
 'Asmat' 'Yahukimo' 'Pegunungan Bintang' 'Tolikara' 'Sarmi' 'Keerom'
 'Waropen' 'Supiori' 'Mamberamo Raya' 'Nduga' 'Lanny Jaya'
 'Mamberamo Tengah' 'Yalimo' 'Puncak' 'Dogiyai' 'Intan Jaya' 'Deiyai'
 'Kota Jayapura']
--------------------

Karena data saya berisi Provinsi beserta Kabupaten/Kota yang berbeda-beda, jadi tidak ada yang perlu ditangani.

**Construct Data**

Berdasarkan korelasi yang telah ada, saya ingin menganalisis mengenai pengaruh pendidikan terhadap perekonomian di wilayah tersebut dan pengaruh pendidikan terhadap kemiskinan.

In [66]:
df["education_income_ratio"] = df["avg_schooltime"] / df["exp_percap"]
df["education_poverty_index"] = df["poorpeople_percentage"] / df["avg_schooltime"]

df

,province,cities_reg,poorpeople_percentage,reg_gdp,life_exp,avg_schooltime,exp_percap,education_income_ratio,education_poverty_index
0,Aceh,Simeulue,18.98,2.275,65.240,9.48,7148,0.001326,2.002110
1,Aceh,Aceh Singkil,20.36,2.425,67.355,8.68,8776,0.000989,2.345622
2,Aceh,Aceh Selatan,13.18,5.531,64.360,8.88,8180,0.001086,1.484234
3,Aceh,Aceh Tenggara,13.41,5.063,68.155,9.67,8030,0.001204,1.386763
4,Aceh,Aceh Timur,14.45,10.616,68.705,8.21,8577,0.000957,1.760049
...,...,...,...,...,...,...,...,...,...
509,Papua,Puncak,36.26,1.438,66.060,2.16,5412,0.000399,16.787037
510,Papua,Dogiyai,28.81,1.356,65.845,4.94,5415,0.000912,5.831984
511,Papua,Intan Jaya,41.66,1.274,65.580,3.09,5328,0.000580,13.482201
512,Papua,Deiyai,40.59,1.439,65.355,3.25,4673,0.000695,12.489231
513,Papua,Kota Jayapura,11.39,32.207,70.455,11.57,14937,0.000775,0.984443

**Data Reduction**

Karena kolom "life_exp", dan "reg_gdp" tidak berkaitan dengan analisis saya, saya akan menghapus kolom tersebut.

In [67]:
df = df.drop('life_exp', axis=1)
df = df.drop('reg_gdp', axis=1)

df

,province,cities_reg,poorpeople_percentage,avg_schooltime,exp_percap,education_income_ratio,education_poverty_index
0,Aceh,Simeulue,18.98,9.48,7148,0.001326,2.002110
1,Aceh,Aceh Singkil,20.36,8.68,8776,0.000989,2.345622
2,Aceh,Aceh Selatan,13.18,8.88,8180,0.001086,1.484234
3,Aceh,Aceh Tenggara,13.41,9.67,8030,0.001204,1.386763
4,Aceh,Aceh Timur,14.45,8.21,8577,0.000957,1.760049
...,...,...,...,...,...,...,...
509,Papua,Puncak,36.26,2.16,5412,0.000399,16.787037
510,Papua,Dogiyai,28.81,4.94,5415,0.000912,5.831984
511,Papua,Intan Jaya,41.66,3.09,5328,0.000580,13.482201
512,Papua,Deiyai,40.59,3.25,4673,0.000695,12.489231
513,Papua,Kota Jayapura,11.39,11.57,14937,0.000775,0.984443